linters-settings:
  gofmt:
    simplify: true
  misspell:
    locale: US
  gofumpt:
    lang-version: "1.16"
    extra-rules: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/woodpecker-ci/woodpecker)

linters:
  enable:
    - bidichk
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - whitespace
    - gofumpt
    - asciicheck
    - bodyclose
#    - contextcheck
#    - cyclop
    - depguard
    - dogsled
#    - dupl
    - durationcheck
#    - errchkjson
#    - errname
#    - errorlint
#    - exhaustivestruct
#    - exhaustive
#    - exportloopref
#    - forbidigo
#    - forcetypeassert
    - gci
#    - gochecknoglobals
#    - gochecknoinits
#    - gocognit
#    - goconst
#    - gocritic
#    - gocyclo
    - goheader
    - goimports
#    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
#    - gosec
#    - ifshort
    - importas
#    - ireturn
#    - lll
    - makezero
#    - nakedret
#    - nestif
#    - nilerr
#    - nilnil
#    - nlreturn
#    - noctx
    - nolintlint
#    - paralleltest
#    - prealloc
#    - predeclared
#    - promlinter
    - rowserrcheck
    - sqlclosecheck
#    - stylecheck
#    - tagliatelle
#    - tenv
#    - testpackage
#    - thelper
#    - tparallel
    - unconvert
#    - unparam
    - wastedassign
    - whitespace
#    - wrapcheck
#    - wsl

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: woodpecker-go/woodpecker/client.go|server/swagger/swagger.go
      linters:
        - deadcode
        - unused
