FROM alpine:3.13
RUN apk add go make sqlite
COPY . .
RUN make release

FROM alpine:3.13

RUN apk add -U --no-cache ca-certificates

ENV GODEBUG=netdns=go
# ADD release/drone-agent /bin/
COPY --from=0 release/drone-agent /bin/

EXPOSE 3000
HEALTHCHECK CMD ["/bin/drone-agent", "ping"]

ENTRYPOINT ["/bin/drone-agent"]

