labels:
  backend: lxc

variables:
  - &go_version "1.19.5"
  - &when_path
      - ".woodpecker/lxc.yml"
      - "pipeline/backend/lxc/**"

pipeline:
   lxc:
     image: debian:bullseye
     commands: |
       apt-get install -qq -y wget git git-lfs make
       wget --quiet -O /bin/plugin-git https://github.com/woodpecker-ci/plugin-git/releases/download/v2.0.3/linux-amd64_plugin-git && chmod +x /bin/plugin-git

       wget --quiet -c https://go.dev/dl/go$$GO_VERSION.linux-amd64.tar.gz
       tar -C /usr/local -xzf go$$GO_VERSION.linux-amd64.tar.gz
       export PATH=$$PATH:/usr/local/go/bin
       export GOPATH=/woodpecker/go
       export HOME=/woodpecker

       make build-cli

       CLASS_C=10.0.8 pipeline/backend/lxc/tests/lxc.sh

       PATH=$$(pwd)/dist:$$PATH pipeline/backend/lxc/tests/run.sh

     environment:
       GO_VERSION: *go_version
     when:
       path: *when_path
